name: CI
on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5

      - name: Install Nim
        uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: "2.2.10"

      - name: Install dependencies
        run: nimble install -y --depsOnly

      - name: Run tests
        run: testament pattern "tests/test_*.nim"
